services:
  smtp-teams-bridge:
    image: disposablethought/smtp-teams-bridge:latest
    ports:
      - "${SMTP_PORT:-25}:25"
    environment:
      - WEBHOOK_URL=${TEAMS_WEBHOOK_URL}
      - SMTP_PORT=${SMTP_PORT:-25}
    restart: always
    networks:
      - smtp_net

networks:
  smtp_net:
    driver: bridge
